apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookerie-backend-deployment
  labels:
    app: bookerie-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookerie-backend
  template:
    metadata:
      labels:
        app: bookerie-backend
    spec:
      containers:
        - name: bookerie-backend
          image: bhaskar1612/bookerie-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: bookerie-backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: bookerie-backend-service
spec:
  selector:
    app: bookerie-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer